# Generated by Django 5.2.1 on 2025-11-15 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(unique=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("access", "Access Token"),
                            ("refresh", "Refresh Token"),
                        ],
                        max_length=10,
                    ),
                ),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "tblTokenBlacklisted",
            },
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
                ("attempt_count", models.IntegerField(default=0)),
                ("channel", models.CharField(max_length=20)),
                ("purpose", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "tblOTP",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_token", models.CharField(max_length=512)),
                ("refresh_token", models.CharField(max_length=512)),
                (
                    "device_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("login_at", models.DateTimeField(auto_now_add=True)),
                ("logout_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "tblUserSession",
            },
        ),
    ]
